# docker-compose.yml
version: '3.3'

services:
  laracom-user-service:
    depends_on:
      - laracom-user-db
    build:
      ./user-service
    ports:
      - 9091:9091
    environment:
      MICRO_SERVER_ADDRESS: ":9091"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "laracom-user-db:3306"
      DB_NAME: "laracom_user"
      DB_USER: "root"
      DB_PASSWORD: "123456"

  laracom-user-cli:
    build: ./user-cli
    environment:
      MICRO_REGISTRY: "mdns"

  laracom-user-db:
    image: mysql:5.7
    container_name: laracom-user-db
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: "laracom_user"
      MYSQL_ROOT_PASSWORD: "123456"

  laracom-micro-api:
    image: micro/micro:v2.9.3
    environment:
      MICRO_REGISTRY: "mdns"
    links:
      - laracom-user-service
    ports:
      - 8080:8080
    command: api --handler=rpc --namespace=laracom --type=service --enable_rpc

volumes:
  db_data: {}